/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/5.2.1/userguide/multi_project_builds.html
 */

rootProject.name = "pylons_wallet"

include(":protos", ":txutil", ":walletcore", ":devwallet", ":httpipc", ":devdevwallet", ":libpylons",
    ":recipetool", ":droidwallet")

pluginManagement {
    repositories {
        mavenLocal()
        jcenter()
        gradlePluginPortal()
        mavenCentral()

        maven(url = "https://jitpack.io")
        google()
    }
}