package com.pylons.wallet.libkylons.constants

class Keys {
    companion object {
        const val INFO = "INFO"
        const val ADDRESS = "ADDRESS"
        const val NAME = "NAME"
        const val COIN_DENOMS = "COIN_DENOMS"
        const val COIN_COUNTS = "COIN_COUNTS"
        const val ITEMS = "ITEMS"
        const val TX = "TX"
        const val ACTION = "ACTION"
        const val TYPE = "TYPE"
        const val SUCCESS = "SUCCESS"
        const val TIMESTAMP = "TIMESTAMP"
        const val MESSAGES = "MESSAGES"
        const val EXECUTIONS = "EXECUTIONS"
        const val PYLONS = "PYLONS"
        const val COIN_INPUTS = "COIN_INPUTS"
        const val ITEM_INPUTS = "ITEM_INPUTS"
        const val COOKBOOK = "COOKBOOK"
        const val RECIPE = "RECIPE"
        const val DESCRIPTION = "DESCRIPTION"
        const val DEVELOPER = "DEVELOPER"
        const val VERSION = "VERSION"
        const val SUPPORT_EMAIL = "SUPPORT_EMAIL"
        const val COST_PER_BLOCK = "COST_PER_BLOCK"
        const val LEVEL = "LEVEL"
        const val OUTPUT_TABLES = "OUTPUT_TABLES"
        const val OUTPUTS = "OUTPUTS"
        const val BLOCK_INTERVAL = "BLOCK_INTERVAL"
        const val ID = "ID"
        const val RECIPE_TYPE = "RECIPE_TYPE"
        const val UPGRADE_PARAM = "UPGRADE_PARAM"
        const val COINS = "coins"
        const val ERROR = "error"
        const val ERROR_CODE = "errorCode"
        const val EXEC_ID = "EXEC_ID"
        const val PAY_TO_COMPLETE = "PAY_TO_COMPLETE"

        const val EXCEPTION = "exception"
        const val MESSAGE = "message"
        const val STACK_TRACE = "stackTrace"
    }
}