package com.pylons.wallet.core.constants

class Keys {
    companion object {
        const val COINS = "coins"
        const val ERROR = "error"
        const val ERROR_CODE = "errorCode"
        const val ADDRESS = "address"
        const val INFO = "info"
        const val ITEMS = "items"
        const val NAME = "name"
        const val PROFILE_EXISTS = "profileExists"
        const val PYLONS = "pylons"
        const val SUCCESS = "success"
        const val OTHER_ADDRESS = "otherProfileId"
        const val COINS_IN = "coinsIn"
        const val COINS_OUT = "coinsOut"
        const val ITEMS_IN = "itemsIn"
        const val ITEMS_OUT = "itemsOut"
        const val RECIPE = "recipe"
        const val COOKBOOK = "cookbook"
        const val PREFERRED_ITEMS = "preferredItemIds"
        const val STRINGS = "strings"
        const val JSON = "json"
        const val FRIENDS = "friends"
        const val TX = "tx"
        const val EXCEPTION = "exception"
        const val MESSAGE = "message"
        const val STACK_TRACE = "stackTrace"
        const val DEVELOPER = "developer"
        const val DESCRIPTION = "description"
        const val SUPPORT_EMAIL = "supportEmail"
        const val VERSION = "version"
        const val LEVEL = "level"
        const val REQUESTER = "requester"
        const val COSTPERBLOCK = "costPerBlock"
    }
}